# Change the default Omarchy look'n'feel

# Border colors applied after theme (this file is sourced later in hyprland.conf)
$activeBorderColor = rgba(33ccffee) rgba(00ff99ee) 45deg
$inactiveBorderColor = rgba(595959aa)

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor

    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
    col.border_locked_active = $activeBorderColor
    col.border_locked_inactive = $inactiveBorderColor
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
